title: Ben's Test Site
collections:
  linux:
    output: true
    permalink: /linux/:path/
  HPC:
    output: true
    permalink: /HPC/:path/

# build
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
  
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "contrast"
search                   :  true #, false (default)
search_full_content      :  false #, false (default)
#Note: Only the first 50 words of a post or page’s body content is added to the Lunr search index. Setting search_full_content to true in your _config.yml will override this and could impact page load performance.
search_provider          :  lunr #(default), algolia
