title: Ben's Test Site
collections:
  linux:
    output: true
    permalink: /linux/:path/
  HPC:
    output: true
    permalink: /HPC/:path/

# Tipue search settings
tipue_search:
  include:
    pages: true
    collections: [linux, HPC]

# build
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "contrast"
