title: Ben's Test Site
collections:
  linux:
    output: true
    permalink: /linux/:path/
  HPC:
    output: true
    permalink: /HPC/:path/

# Tipue search settings
tipue_search:
  include:
    pages: true
    collections: [linux, HPC]

# build
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
